Pytorch profiler
nicolas-chaulet/torch-points3d pull request #673
Opened 2021-09-21 09:02 UTC by nicolas-chaulet

2021-09-24 16:21 UTC, CCInc requested changes
Awesome!

2021-09-24 16:21 UTC, CCInc commented on torch_points3d/trainer.py
> +            schedule=torch.profiler.schedule(
Can we refactor this into its own function to either return a profile or nullcontext?

2021-09-24 16:21 UTC, CCInc commented on torch_points3d/trainer.py
> +                with (torch.profiler.record_function('train_epoch') if self.pytorch_profiler_log else nullcontext()):
Maybe refactor this too?

2021-09-27 14:21 UTC, ggrzeczkowicz commented on torch_points3d/trainer.py
> +            schedule=torch.profiler.schedule(
Done with #679

2021-09-27 14:21 UTC, ggrzeczkowicz commented on torch_points3d/trainer.py
> +                with (torch.profiler.record_function('train_epoch') if self.pytorch_profiler_log else nullcontext()):
Done with #679

2021-09-27 14:23 UTC, ggrzeczkowicz commented
I refactor torch.profiler.profile and torch.profiler.record_function to use own functions and I move call to profile inside _train_epoch in #679

2021-09-30 08:29 UTC, nicolas-chaulet commented
@ggrzeczkowicz looks like static checks are failing, could you please take a look? 
```
make staticchecks
```

2021-11-09 09:54 UTC, ggrzeczkowicz commented
I think you could merge that, unless the codecov is a problem.

2021-11-09 18:19 UTC, merged